substitutions:
  _REGION: us-west1
  _REPO: cloud-run-source-deploy
  _SERVICE: cadastra-yduqs-main-git
  _IMAGE: cadastra-yduqs-main-git
  _CONTEXT_DIR: apis
  # se seu Dockerfile estiver com outro nome/caminho, ajuste aqui:
  _DOCKERFILE: Dockerfile

steps:
  # Build (contexto = apis/)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f', '${_CONTEXT_DIR}/${_DOCKERFILE}',
        '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA',
        '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:latest',
        '${_CONTEXT_DIR}'
      ]

  # Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:latest']

  # Deploy Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      [
        'gcloud', 'run', 'deploy', '${_SERVICE}',
        '--image', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA',
        '--region', '${_REGION}',
        '--platform', 'managed',
        '--quiet'
      ]

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:latest'
